name       : kseexpr
version    : 4.0.1.0
release    : 1
source     :
    - https://download.kde.org/stable/kseexpr/4.0.1/kseexpr-4.0.1.0.tar.gz : 13b8455883001668f5d79c5734821c1ad2a0fbc91d019af085bb7e31cf6ce926
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : An embeddable expression evaluation engine
description: |
    KSeExpr is an embeddable, arithmetic expression language that enables you to write shader-like scripts.
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
